### PR TITLE
Made a majority of the components responsive

### PR DESCRIPTION
**Pull request by IanWoodard**
Currently, besides a few small outliers that I will try to find and clean up, the pool select and pool page should be responsive. I do want to warn you that there may be small visual bugs that may come up that I have yet to discover, but do note that this will make the app much much easier to use on any mobile platform than it ever has been. Feel free to leave some comments/questions about anything. Also, the portfolio page is mostly responsive, but since we are not shipping it right away I will hold off on working on it for the time being. As usual, below I attached some images of the components:
navbar-dropdown
blend-pools-mobile-1
blend-pools-mobile-2
blend-pools-mobile-3
blend-pools-mobile-4
pool-mobile-1
pool-mobile-2
pool-mobile-3
pool-mobile-4
pool-mobile-5
pool-mobile-6
pool-mobile-7

### CODE REVIEW

**Review by haydenshively — COMMENTED** [review]
This looks great. Definitely want to merge it in before tomorrow. Only thing I would suggest is that as width shrinks on the Pool Details Page, the Deposit/Withdraw tabs should move _below_ the graph, not above it (imho)

**Comment by IanWoodard** [comment]
> This looks great. Definitely want to merge it in before tomorrow. Only thing I would suggest is that as width shrinks on the Pool Details Page, the Deposit/Withdraw tabs should move _below_ the graph, not above it (imho)

Sure thing

**Comment by IanWoodard** [comment]
Just a heads up, the way I ended up putting the interaction tabs below the graph on smaller screens is not the best way to do it, but it is the most time-efficient way and honestly doesn't add too much complexity so as long as we don't continue down this path with other components, all should be good. With that being said, I don't think we will need to for other components as they won't require the amount of refactoring that the interaction tabs would have.

**Review by haydenshively — APPROVED** [review]
Can you just add an issue here on Github to remind us to re-examine the way its done?

**Pull request merged**
