### PR TITLE
Added token pair header component

### PR DESCRIPTION
**Pull request by IanWoodard**
Added the Token Pair Header component based on the Figma spec. In doing so, I refactored a bit of the portfolio card code to allow me to reuse some things. Additionally, if it looks a bit off, it is most likely due to the difference in fonts. Once the new fonts are added, they should look fully up to spec.

As usual, I attached an image of the component below:
tokenpairheader

### CODE REVIEW

**Comment by haydenshively** [comment]
What do we need to do to get the fonts in place?

**Comment by IanWoodard** [comment]
Will add the fonts to this PR. I am not sure how the license works, but it seems to be free to use. [https://www.fontshare.com/terms#notice-to-user](https://www.fontshare.com/terms#notice-to-user)

**Comment by IanWoodard** [comment]
@haydenshively Fonts should be added. Let me know what you think. I did some initial cleaning up of existing components. I will continue to fix other components up when this is merged. I realize the font may flash on load for a second. This is to be expected. If you all would like I could work on making it seamless by using prefetching and font-swapping.

**Review by adamegyed — APPROVED** [review]
Looks good to me. We can also begin using the added fonts elsewhere after merging this, and it appears the licenses are being handled appropriately.

**Pull request merged**
