### PR TITLE
Adding browse search component

### PR DESCRIPTION
**Pull request by IanWoodard**
Adding search component for browse page that meets the new spec from Figma. However, the Figma was not exhaustive so there is some ambiguity. Let me know what can be improved and I will fix it accordingly.

As per usual, below I attached some images:

Default:
searchcomponent1
Hover:
searchcomponenthover1
Focus:
searchcomponentfocus1

### CODE REVIEW

**Comment by haydenshively** [comment]
Here's a fuller spec. Just a few minor differences:
image

**Comment by IanWoodard** [comment]
@haydenshively One thing I am confused about is the default state. I noticed in the spec you sent, the default state has the icon colored the same as the text, but in the browse pools spec, the icon is a white color. Which spec should I follow for that?
searchdefault

**Comment by IanWoodard** [comment]
@haydenshively Also, I am confused about the active vs focus state from the spec. I just want to make sure these terms mean the same thing I think they mean based on the mdn docs. The active state is when an element is clicked on [https://developer.mozilla.org/en-US/docs/Web/CSS/:active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active) and the focus state is when an element has focus [https://developer.mozilla.org/en-US/docs/Web/CSS/:focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus) is this what the spec is describing?

**Comment by adamegyed** [comment]
You are correct with you assessment of active and focus states. Active should take priority over focus, including after making the element active through means other than clicking (i.e. tabbing to the element, pressing enter, then starting typing). However, I am unsure if the search spec should be identical to the design system spec here, given that we're seeing some inconsistency. Let's implement up to design system spec for now and change if problems arise later.

**Comment by IanWoodard** [comment]
Added standardized input components in place of the original intent of this PR. As of now, these inputs are being used in place of all use cases of text/number inputs except for the one associated with max slippage as that component does not fit the input spec and would require a lot of additional changes for a one-off component. To access the examples of all of the included inputs, I will be adding a route to it at `/inputs`.

inputs1
inputs2

**Comment by IanWoodard** [comment]
@adamegyed take a look when you get the chance, a lot has changed.

**Review by adamegyed — APPROVED** [review]
Looks good! Great usage of Tailwind. Before merging, could you remove the inputs example page from the router (will add back in the dev-only router later), and could you add an optional field to the icon inputs that has onClick behavior for the icon? While it might not always be necessary, for something like a search icon it would make sense to have clicking the search icon trigger a search start.

**Pull request merged**
